version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: "fresh"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    container_name: stubro_mysql
    image: mysql:8.0
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "db-password"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
