/*
 * openapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	config "github.com/kazukitaninaka/stubro-server/config"
	openapi "github.com/kazukitaninaka/stubro-server/openapi"
)

func main() {
	openapi.InitDb()
	log.Printf("Server started")
	config.InitFirebase()

	ConsultationApiService := openapi.NewConsultationApiService()
	ConsultationApiController := openapi.NewConsultationApiController(ConsultationApiService)

	MentorApiService := openapi.NewMentorApiService()
	MentorApiController := openapi.NewMentorApiController(MentorApiService)

	TermApiService := openapi.NewTermApiService()
	TermApiController := openapi.NewTermApiController(TermApiService)

	TypeApiService := openapi.NewTypeApiService()
	TypeApiController := openapi.NewTypeApiController(TypeApiService)

	UserApiService := openapi.NewUserApiService()
	UserApiController := openapi.NewUserApiController(UserApiService)

	router := openapi.NewRouter(ConsultationApiController, MentorApiController, TermApiController, TypeApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
