/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ConsultationApiService := openapi.NewConsultationApiService()
	ConsultationApiController := openapi.NewConsultationApiController(ConsultationApiService)

	MentorApiService := openapi.NewMentorApiService()
	MentorApiController := openapi.NewMentorApiController(MentorApiService)

	UserApiService := openapi.NewUserApiService()
	UserApiController := openapi.NewUserApiController(UserApiService)

	router := openapi.NewRouter(ConsultationApiController, MentorApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
