/*
 * openapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"
	"os"

	config "github.com/kazukitaninaka/stubro-server/config"
	openapi "github.com/kazukitaninaka/stubro-server/openapi"
)

func main() {
	openapi.InitDb()
	log.Printf("Server started")
	config.InitFirebase()

	router := openapi.NewRouter(openapi.NewController())

	log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), router))
}
