/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A TermApiController binds http requests to an api service and writes the service results to the http response
type TermApiController struct {
	service TermApiServicer
}

// NewTermApiController creates a default api controller
func NewTermApiController(s TermApiServicer) Router {
	return &TermApiController{service: s}
}

// Routes returns all of the api route for the TermApiController
func (c *TermApiController) Routes() Routes {
	return Routes{
		{
			"GetTerms",
			strings.ToUpper("Get"),
			"/terms",
			c.GetTerms,
		},
	}
}

// GetTerms - Get all terms
func (c *TermApiController) GetTerms(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTerms()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
