/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "gorm.io/gorm"

type Consultation struct {
	*gorm.Model

	ConsultationRequest

	User User `json:"user"`

	Mentor Mentor `json:"mentor"`

	IsPaymentDone bool `json:"isPaymentDone"`
}
