/*
 * openapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserRequest struct {

	Username string `json:"username,omitempty"`

	// If a new email is given, the user's email verified property will be set to false.
	Email string `json:"email,omitempty"`
}

// AssertUserRequestRequired checks if the required fields are not zero-ed
func AssertUserRequestRequired(obj UserRequest) error {
	return nil
}

// AssertRecurseUserRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserRequest (e.g. [][]UserRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserRequest, ok := obj.(UserRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserRequestRequired(aUserRequest)
	})
}
