/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {

	Username string `json:"username,omitempty"`

	// If a new email is given, the user's email verified property will be set to false.
	Email string `json:"email,omitempty"`
}
