/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// UserApiService is a service that implents the logic for the UserApiServicer
// This service should implement the business logic for every endpoint for the UserApi API.
// Include any external packages or services that will be required by this service.
type UserApiService struct {
}

// NewUserApiService creates a default api service
func NewUserApiService() UserApiServicer {
	return &UserApiService{}
}

// GetUserByUserId - Get User Info by User ID
func (s *UserApiService) GetUserByUserId(userId int) (interface{}, error) {
	// TODO - update GetUserByUserId with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUserByUserId' not implemented")
}

// GetUsers - Get all users
func (s *UserApiService) GetUsers() (interface{}, error) {
	// TODO - update GetUsers with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUsers' not implemented")
}

// PatchUsersUserId - Update User Information
func (s *UserApiService) PatchUsersUserId(userId int, inlineObject InlineObject) (interface{}, error) {
	// TODO - update PatchUsersUserId with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PatchUsersUserId' not implemented")
}

// PostUser - Create New User
func (s *UserApiService) PostUser(user User) (interface{}, error) {
	// TODO - update PostUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	if err := Db.FirstOrCreate(&user, User{Uid: user.Uid}).Error; err != nil {
		return nil, errors.New("err!")
	}
	return user, nil
}
