/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"log"
)

// TypeApiService is a service that implents the logic for the TypeApiServicer
// This service should implement the business logic for every endpoint for the TypeApi API.
// Include any external packages or services that will be required by this service.
type TypeApiService struct {
}

// NewTypeApiService creates a default api service
func NewTypeApiService() TypeApiServicer {
	return &TypeApiService{}
}

// GetTypes - Get all Types
func (s *TypeApiService) GetTypes() (interface{}, error) {
	// TODO - update GetTypes with the required logic for this service method.
	// Add api_Type_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	var mentors []Mentor
	if err := Db.Preload("Term", excludeUnnecessaryFields).Preload("Types", excludeUnnecessaryFields).Omit("created_at, updated_at, deleted_at").Find(&mentors).Error; err != nil {
		log.Fatal(err)
		return nil, err
	}
	return mentors, nil
	// return nil, errors.New("service method 'GetMentors' not implemented")
}
