/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A TypeApiController binds http requests to an api service and writes the service results to the http response
type TypeApiController struct {
	service TypeApiServicer
}

// NewTypeApiController creates a default api controller
func NewTypeApiController(s TypeApiServicer) Router {
	return &TypeApiController{service: s}
}

// Routes returns all of the api route for the TypeApiController
func (c *TypeApiController) Routes() Routes {
	return Routes{
		{
			"GetTypes",
			strings.ToUpper("Get"),
			"/types",
			c.GetTypes,
		},
	}
}

// GetTypes - Get all Types
func (c *TypeApiController) GetTypes(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTypes()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
