/*
 * openapi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserRequest1 struct {

	Username string `json:"username,omitempty"`

	// If a new email is given, the user's email verified property will be set to false.
	Email string `json:"email,omitempty"`
}

// AssertUserRequest1Required checks if the required fields are not zero-ed
func AssertUserRequest1Required(obj UserRequest1) error {
	return nil
}

// AssertRecurseUserRequest1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserRequest1 (e.g. [][]UserRequest1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserRequest1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserRequest1, ok := obj.(UserRequest1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserRequest1Required(aUserRequest1)
	})
}
