/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse200 struct {

	UserId float32 `json:"userId"`

	MentorId float32 `json:"mentorId"`

	DesirableDate string `json:"desirableDate"`

	Message string `json:"message"`

	Id float32 `json:"id,omitempty"`
}
