/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject2 struct {
	Username string `json:"username"`

	Email string `json:"email"`

	Image string `json:"image"`

	Destination string `json:"destination"`

	EduOrg string `json:"eduOrg"`

	Term string `json:"term"`

	Type []string `json:"type"`

	Price int `json:"price"`
}
