/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "gorm.io/gorm"

// Mentor - Mentor's information
type Mentor struct {
	*gorm.Model
	ID uint `json:"id"`

	Username string `json:"username"`

	Email string `json:"email,omitempty"`

	Image string `json:"image,omitempty"`

	ClickCount int `json:"clickCount"`

	Destination string `json:"destination"`

	EduOrg string `json:"eduOrg"`

	TermID uint `json:"-"`

	Term Term `json:"term"`

	Types []Type `json:"type" gorm:"many2many:type_mentors;"`

	Price int `json:"price"`
}
